[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[build]
  command = "hugo"
  base = "exampleSite"
  publish = "exampleSite/public"

[build.environment]
  HUGO_VERSION = "0.124.1"
