theme: jekyll-theme-cayman
title: Fokus Hugo Theme
description: Fokus is a free starter template built with Hugo and Bootstrap, providing everything you need to start your Hugo project.
show_downloads: true
google_analytics: G-MKQK789F6L
